import React from 'react'

const initialState = {"AuthData":  {
    "logInfetchError": false,
    "logInfetchLoading": false,
    "loggedIn": false,
    "password": null,
    "resetPasswordEmailSent": false,
    "resetPasswordFetchError": false,
    "resetPasswordLoading": false,
    "signUpFetchError": false,
    "signUpFetchLoading": false,
    "token": null,
    "username": null,
  },
  "Fitness":  {
    "currentStepCount": undefined,
    "dailyStepGoal": 10000,
    "fetchDailyStepsError": false,
    "fetchDailyStepsLoading": false,
  },
  "FriendsAndMsgs":  {
    "allUsers":  [],
    "fetchFriendsError": false,
    "fetchFriendsLoading": false,
    "fetchPendingFriendRequestsError": false,
    "fetchPendingFriendRequestsLoading": false,
    "fetchSingleMessagesError": false,
    "fetchSingleMessagesLoading": false,
    "fetchUsersError": false,
    "fetchUsersLoading": false,
    "friendsList":  [],
    "pendingFriendRequests":  [],
    "singleMessages": undefined,
  },
  "Mood":  {
    "fetchMoodDataError": false,
    "fetchMoodDataLoading": false,
    "moodDates": undefined,
    "moodPastMonth": undefined,
    "moodPastWeek": undefined,
  },
  "ProfileData":  {
    "fetchUserDataError": false,
    "fetchUserDataLoading": false,
    "generalUserData":  {
      "first_name": 'First Name',
      "last_name": 'Last Name',
    },
    "userHealthData":  {
      "DOB":  {
        "month": undefined,
        "year": undefined,
      },
      "gender": undefined,
      "height": undefined,
      "weight": undefined,
    },
  },
  "meditation":  {
    "audioState":  {
      "currentIndex": 0,
      "isBuffering": true,
      "isPlaying": false,
      "isReady": false,
      "playbackInstance": null,
      "volume": 1,
    },
    "courseData":  [],
    "favoriteMeditations":  [],
    "fetchCourseDataError": false,
    "fetchCourseDataLoading": false,
    "fetchCoursesError": false,
    "fetchCoursesLoading": false,
    "fetchFeelingsError": false,
    "fetchFeelingsLoading": false,
    "filteredMeditations":  [],
    "filters":  {
      "testAdvancedFilter": false,
      "testAnxietyFilter": false,
      "testBegginerFilter": false,
      "testConfidenceFilter": false,
      "testDepressionFilter": false,
      "testFavoriteFilter": false,
    },
    "meditations":  [],
    "myFeelings":  {
      "anxious": 1,
      "depressed": 1,
      "excited": 1,
      "lost": 1,
      "stressed": 1,
    },
  },
}

export default initialState